name: Run Accuracy Tracker

on:
  schedule:
    - cron: "15 * * * *"  # Every hour at 15 past
  workflow_dispatch:      # Allow manual trigger

jobs:
  track-accuracy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pandas requests

      - name: Restore last_checked.txt cache
        uses: actions/cache@v3
        with:
          path: last_checked.txt
          key: last-checked

      - name: Run accuracy tracker
        env:
          IFTTT_ACCURACY_URL: ${{ secrets.IFTTT_ACCURACY_URL }}
        run: python track_accuracy.py
